### Site Settings ###
title               : Alex escribe cosas
description         : >-
                      "Me interesa la filosofía, la política y la economía y la intersección entre ellas.
                      Tengo opiniones que nadie pidió sobre muchas cosas. Casi politólogo."
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : Alex-writes-something/alex-writes-something.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : YoussefRaafatNasry/portfolYOU@v2.2.2


### Plugins ###
plugins:
  - jemoji

### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - pages/projects.html


### Author Info ###
author:
  name              : Alex Ramírez
  image             : https://scontent.fbjx1-1.fna.fbcdn.net/v/t1.0-9/107087685_3379280502134462_9184700598414697170_n.jpg?_nc_cat=101&_nc_sid=09cbfe&_nc_ohc=aQIMiku76OAAX-Y0-I9&_nc_ht=scontent.fbjx1-1.fna&oh=91cc39de38990267c65b9d0e1b43b5e0&oe=5F235D8E
# behance           : your_username
# dribbble          : your_username
  email             : alexwritessomething@icloud.com
# facebook          : jaime.fag
  github            : Alex-writes-something
# gitlab            : your_username
  instagram         : alexkonnichiwa
# kaggle            : your_username
  ko-fi             : alexkonnichiwa
# linkedin          : your_username
# medium            : iJaimeFco
# soundcloud        : your_username
# spotify           : 1285425450
# stackoverflow     : your_user_id
# tumblr            : historiasdeunavida.tumblr.com
# twitch            : your_username
  twitter           : alexkonnichiwa
# vimeo             : your_username
#  youtube           : channel/UCq-QDT1S3MdaR12DChoitDg


### Posts ###
permalink: /blog/:title



### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name

### Disqus ###
disqus: jaimefco                          # Your website Shortname on disqus


### Defaults for collections ###
defaults:
  # - scope:
  #     path: ""
  #     type: "projects"
  #   values:
  #     layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
